"""Add cnss_number check constraint

Revision ID: 4ecafb05c8fc
Revises: 55d16c110e79
Create Date: 2025-05-17 16:02:20.815701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecafb05c8fc'
down_revision: Union[str, None] = '55d16c110e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ###  i  added this copnstraint manually because sql alchemy didnt detect it ###
    op.create_check_constraint(
    'ck_employees_cnss_number',
    'employees',
    r"(contract_type IN ('Cdi', 'Cdd') AND cnss_number IS NOT NULL AND cnss_number ~ '^\d{8}-\d{2}$') OR (contract_type IN ('Apprenti', 'Sivp') AND (cnss_number IS NULL OR cnss_number ~ '^\d{8}-\d{2}$'))"
)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_employees_cnss_number', 'employees', type_='check')
    # ### end Alembic commands ###
